server:
  port: 8082

spring:
  application:
    name: feignclient-bean-config

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL

logging.level.com.example.feignclient.feign.clients.RestClient: DEBUG
logging.level.com.example.feignclient.feign.clients.CardClient: DEBUG
